[search_parameters]
locations = ["remote"]
keywords = ["Software Engineer", "Data Analyst"]
exclusion_keywords = ["Senior", "Lead", "Manager"]

[resume]
text = "Your default resume text here."

[prompts]
evaluation_prompt = "Default evaluation prompt here."

[api_keys]
google_api_key = "YOUR_GOOGLE_API_KEY_HERE"
openai_api_key = "YOUR_OPENAI_API_KEY_HERE"

[general]
ai_provider = "gemini" 